drm: msm: sde: Fix compile warnings
Fix the following compiler warning(s) from gcc 6.1.1 with -Werror enabled:

 msm/sde/sde_kms.c:2672:2: error: ignoring return value of
   'drm_atomic_set_crtc_for_connector', declared with
   attribute warn_unused_result [-Werror=unused-result]

 msm/sde/sde_kms.c:2674:2: error: ignoring return value of
   'drm_atomic_commit', declared with attribute warn_unused_result
   [-Werror=unused-result]

Change-Id: I4cf8f050927cadc51622fb059e622261609bd247
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>